services:
  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - STORE_CORS=${STORE_CORS}
      - ADMIN_CORS=${ADMIN_CORS}
      - AUTH_CORS=${AUTH_CORS}
      - REDIS_URL=${REDIS_URL}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - DISABLE_MEDUSA_ADMIN=${DISABLE_MEDUSA_ADMIN}
      - MEDUSA_WORKER_MODE=${MEDUSA_WORKER_MODE}
      - S3_FILE_URL=${S3_FILE_URL}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - STRIPE_API_KEY=${STRIPE_API_KEY}

    # Making the port accessible directly if not using internal nginx
    ports:
      - "9005:9005"